### ISSUE TITLE
Sensors manquants

### ISSUE THREAD

**Issue by DenisLafontTrevisan** [kugan49/veolia-custom-component-HACS#28]
Bonjour,

Dans le tableau de bord Energy il n'y a que le sensor "Last_index" utilisable.

Home Assistant: 2023.12.3

![image](https://github.com/kugan49/veolia-custom-component-HACS/assets/243570/f790c177-496b-4bfe-99c3-d9fb229a5ce5)

**Comment by kugan49** [comment]
Bonjour,
C'est logique : pour le tableau de bord energie il faut un compteur incrémental, donc l'index est l'indicateur idéal.
