### ISSUE TITLE
Problème Installation : https://github.com/kugan49/veolia-custom-component-HACS is not a valid add-on repository

### ISSUE THREAD

**Issue by Sylv1F** [kugan49/veolia-custom-component-HACS#29]
Bonjour,

Je rencontre un problème lors de l'ajout du référentiel :

"https://github.com/kugan49/veolia-custom-component-HACS is not a valid add-on repository"

![image](https://github.com/kugan49/veolia-custom-component-HACS/assets/64889671/af4cc4c3-eebd-4428-8c60-df82fa271ce3)

Je n'ai pas ce problème avec un autre module, une idée de ce qui coince ?

**Comment by kugan49** [comment]
Bonjour, il faut ajouter un dépôt personnalisé de type intégration et c'est là que tu devra mettre cette adresse
