### ISSUE TITLE
My account is linked to www.eau-services.com not www.service.eau.veolia.fr

### ISSUE THREAD

**Issue by SebastienSyd** [kugan49/veolia-custom-component-HACS#3]
## Version of the custom_component

v1.0.3

## Configuration

```yaml

N/A

```

## Describe the bug
When trying to login with my account it says "Username/Password is wrong"
![image](https://user-images.githubusercontent.com/28516084/214593026-8d6cce42-eae9-4415-acb2-32c006dd39c1.png)

I have a Veolia account. I checked the website https://www.service.eau.veolia.fr and I tried to login there but the credentials didn't work. When I want to create a new account it redirects me to the other website: https://www.eau-services.com/ where my credentials work
![image](https://user-images.githubusercontent.com/28516084/214592618-0586f4ff-bb30-4fae-a088-c96bd5b47db6.png)

I suppose they are 2 different websites and probably the API won't work the same way. Can you confirm?

## Debug log

```text

N/A

```

**Comment by kugan49** [comment]
Bonjour @SebastienSyd ,

tu as tout a fait raison.

Le système Veolia est composé de nombreux sites qui ont chacun leur API.
Le composant que j'ai développé n'est donc pas compatible pour toi.
Désolé
