### ISSUE TITLE
Avertissement HomeAssistant - constante à modifier avant HA Core 2025.1

### ISSUE THREAD

**Issue by pics76** [kugan49/veolia-custom-component-HACS#30]
Pas d'urgence mais peut-être à traiter avant les changements...

Logger: homeassistant.const
Source: helpers/deprecation.py:204
First occurred: 4 janvier 2024 à 17:56:11 (1 occurrences)
Last logged: 4 janvier 2024 à 17:56:11

VOLUME_LITERS was used from veolia, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfVolume.LITERS instead, please create a bug report at https://github.com/kugan49/veolia-custom-component-HACS/issues**

**Comment by LGO44** [comment]
Dans entity.py remplacer **from homeassistant.const import VOLUME_LITERS** par **from homeassistant.const import UnitOfVolume**

_entity.py
"""VeoliaEntity class."""
from homeassistant.components.sensor import SensorDeviceClass, SensorEntity
#from homeassistant.const import VOLUME_LITERS
from homeassistant.const import UnitOfVolume
from homeassistant.helpers.update_coordinator import CoordinatorEntity_

**Comment by kugan49** [comment]
https://github.com/kugan49/veolia-custom-component-HACS/releases/tag/v1.3.1
