### ISSUE TITLE
Entités disponibles dans le menu énergie

### ISSUE THREAD

**Issue by flety-emmanuel** [kugan49/veolia-custom-component-HACS#33]
Je souhaitais avoir la consommation journalière dans le menu energie mais elle y était absente (seul l'index est présent)

Pour le daily usage et le monthly usage, il semble qu'il manque juste une info de state_class dans la classe de chaque capteur.
J'ai ajouté:

@property
    def state_class(self):
        """Return the state_class of the sensor."""
        _LOGGER.debug(f"state_class = {SensorStateClass.TOTAL}")
        return SensorStateClass.TOTAL

pour class VeoliaDailyUsageSensor(VeoliaEntity):
et
class VeoliaMonthlyUsageSensor(VeoliaEntity):

et les capteurs apparaissent désormais dans le menu énergie. Je comprends que l'index devrait suffire en étant en total-increasing mais je voulais disposer des 3

**Comment by kugan49** [comment]
Bonjour,

Le module énergie calcule lui même les consos, journalière, mensuelles, etc en fonction de l'index donc je ne comprend pas trop l'objectif de cet ajout.

Que se passe t'il si Veolia ne transmet pas pendant plusieurs jours la consommation journalière ou mensuelle ? Le cumul ne sera pas correct. L'avantage de l'index , est que même en cas de non réception de l'info pendant plusieurs semaines, lors de la réception la valeur transmise représente la totalité de l'eau consommé. On a donc pas d'oubli de conso.

**Comment by flety-emmanuel** [comment]
noté merci bcp. J'ai remis l'index comme traceur de conso merci
