### ISSUE TITLE
Détection écoulement continu

### ISSUE THREAD

**Issue by flety-emmanuel** [kugan49/veolia-custom-component-HACS#34]
Bonjour,
J'ai subi une fuite, détecté par véolia via leur politique de détection d'écoulement continu (c'est le capteur Itron sur le compteur qui s'en occupe et notifie). 
@kugan49 vous semblez avoir une doc détaillée de l'API veolia : cette information figure sur le relevé de conso (j'ai pu vérifier que j'avais bien réparé ma fuite ainsi).
Est il possible de récupérer cette information d'écoulement continu via l'API web / SOAP ? Ca serait super pratique de l'avoir dans le sensor HA, car la limite de notification de veolia est de 10m3 et ca fait 50€+ de perdu, une notif plus précoce serait bien utile
Merci

**Comment by kugan49** [comment]
Bonjour,

Désolé mais je n'ai pas de doc du tout concernant l'API, il s'agit uniquement de reverse engineering via l'appli mobile et l'appli Web.
Je n'ai donc accès qu'aux données de conso passées montrées sur l'appli ou le site web.
J'ai tenté de prendre contact avec eux pour avoir plus de documentation mais sans succès

**Comment by flety-emmanuel** [comment]
merci beaucoup pour votre réponse. je vais voir si je peux trouver l'info. Comment puis je aider à faire du reverse via le site web ? J'ai encore accès à mon écoulement continue dans l'historique. Est ce possible en faisant juste du traçage avec la console du navigateur ? 
![image](https://github.com/kugan49/veolia-custom-component-HACS/assets/11643219/405572ce-4c92-4198-9231-36a17e016d19)
