### ISSUE TITLE
Affichage de la consommation dans Energie

### ISSUE THREAD

**Issue by emi-carus** [kugan49/veolia-custom-component-HACS#36]
Bonjour,

D'abord félicitation pour votre travail.
J'ai remarqué que dans le tableau énergie, la consommation affichée était décalée de 1 jours. Par exemple, la consommation récupée le 8 février est celle du 7 février mais elle s'affiche bien le 8 dans le tableau énergie.

**Comment by kugan49** [comment]
Bonjour,

Oui en effet, je n'ai pas la possibilité de forcer la date dans le tableau énergie : cette date est automatiquement calculé lors de la mise à jour du compteur.
Le souci est que Veolia ne nous fournit pas les données en temps réel mais au mieux avec un jour de retard.
Il se peut donc qu'il y ai plusieurs jours de décalage

**Comment by JKdad77** [comment]
De mon côté j'ai même 2 jours de retards sur le last index 
![image](https://github.com/kugan49/veolia-custom-component-HACS/assets/118446176/7960410f-59e9-48ab-af3a-0e4a0deff9cc)

Ainsi que sur l'index journalier 
![image](https://github.com/kugan49/veolia-custom-component-HACS/assets/118446176/e50d06b4-3dfe-43a5-a988-b73306c1728c)

J'espère que VEOLIA va corriger ce pb pour que le plugin colle au plus prêt de la réalité 

Mais au moins pour suivre la conso mensuel ce sera top 

Merci @kugan49 pour ton œuvre

**Comment by Treenity** [comment]
Salut @kugan49,
Pour ce décalage, je pensais à une solution mais aucune idée pour savoir si c’est réalisable ou pas.
Voilà l’idée:
Chaque jour, créer une valeur « vide »(c’est à dire on prend la dernière valeur connue, on pousse la même.
Exemple: hier 1970L
Aujourd’hui: 1970L
Donc conso aujourd’hui: 0

mais des qu’on reçoit la MAJ de VEOLIA, push les nouvelles valeures aux bonnes dates.

de cette façon on aurai les bonnes conso, aux bons jours.

Par contre cela ne peut marcher qu’à deux conditions:
- le fait de pusher la même valeur que la veille permet de créer un « point ».
- Que depuis le plugin, on puisse modifier les points précédents comme on peut le faire dans le mode dev dans l’onglet statistiques.

**Comment by kugan49** [comment]
> Salut @kugan49, Pour ce décalage, je pensais à une solution mais aucune idée pour savoir si c’est réalisable ou pas. Voilà l’idée: Chaque jour, créer une valeur « vide »(c’est à dire on prend la dernière valeur connue, on pousse la même. Exemple: hier 1970L Aujourd’hui: 1970L Donc conso aujourd’hui: 0
> 
> mais des qu’on reçoit la MAJ de VEOLIA, push les nouvelles valeures aux bonnes dates.
> 
> de cette façon on aurai les bonnes conso, aux bons jours.
> 
> Par contre cela ne peut marcher qu’à trois conditions:
> 
> * le fait de pusher la même valeur que la veille permet de créer un « point ».
> * Que depuis le plugin, on puisse modifier les points précédents comme on peut le faire dans le mode dev dans l’onglet statistiques.
> * que le fait d’éditer une valeur précédente, corrige le tableau « énergie ».

Salut @Treenity,

L'idée est intéressante mais je ne pense pas qu'on puisse faire ce genre de chose, cela donnerait à mon sens des capacités trop intrusives aux intégrations.
