### ISSUE TITLE
Retrying setup: None when trying to install the component, but strangely all the logs seem to be more than OKAY...

### ISSUE THREAD

**Issue by r-jean-pierre** [kugan49/veolia-custom-component-HACS#4]
Hi!

I just tried to use this component, and except login & password I cannot really do any mistake but the integration failed with **"None when trying to install the component"** 
If you read the log file attached, all information is there, from the consumptions up to details about myself and my contract (I obfuscated them but they were detailed and totally correct, it's really my contract and the consumptions are the same as when I login on the website or my phone)

[mylogs.txt](https://github.com/kugan49/veolia-custom-component-HACS/files/10539119/mylogs.txt)

Is there any extra step or something that I need to do?

Thank you for your help

**Comment by kugan49** [comment]
Bonjour,

tes données journalières sont corrects mais il y a un souci sur tes données mensuelles :
Veolia ne fournit que le mois de mars 2021
As tu les mêmes infos sur le site ?

**Comment by r-jean-pierre** [comment]
Hello

Effectivement Veolia est un peu en carafe depuis presque 2 mois... là depuis quelques jours on dirait que ça reprend forme, idem pour l'application android
A ce jour, même sur le site, je n'ai que 1 valeur pour 1 seul mois quand la granularité est le mois:

![2023_01_31_19_49_27_Window](https://user-images.githubusercontent.com/9727894/215854884-3063cf92-f08c-4576-b961-aa7b3081bb5c.png)

Même le titre du graphique est évocateur...

C'est grave pour ton composant? car franchement, ils seraient capables de pas fournir les données historiques... (et éventuellement un nouveau client n'aurait pas encore de données agrégées au niveau du mois)

En tout cas, perso, je préfère laisser HA s'occuper de stocker les données et faire par la suite un grouby-apply-somme

Merci au fait pour ton composant! C'est super cool d'avoir créer un tel outil

**Comment by kugan49** [comment]
Du coup j'ai créé une nouvelle version, la 1.1.1 qui permet justement de passer si l'API ne ramène qu'un résultat

**Comment by r-jean-pierre** [comment]
Hello!

Alors un grand merci: ça fonctionne!

![2023-02-01 09_50_44-Window](https://user-images.githubusercontent.com/9727894/215995449-ee2b1612-b4e1-4d7f-9f24-d79b6a26b7bc.png)

Bien joué, les informations, sont là, j'ai copié l'exemple de la doc pour pas compliquer, et j'ai exactement les données telles que présentées sur le site véolia

Encore merci!
