### ISSUE TITLE
Historisation

### ISSUE THREAD

**Issue by LGO44** [kugan49/veolia-custom-component-HACS#8]
This is a very usefull integration.

It should be nice to archive the data: 
  daily_consumption
  monthly
  yearly.

**Comment by kugan49** [comment]
Salut,

Il s'agit de données Energie, tu retrouves donc les données dans le tableau de bord Energie de Home Assistant.
L'historisation est gérée par cet écran

**Comment by LGO44** [comment]
Merci beaucoup pour ces infos, ça me va très bien.
Peut être serait-il bon de le notifier dans la doc de l'integration 👍
